// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_ControleDespesas.Data;

#nullable disable

namespace Projeto_ControleDespesas.Migrations
{
    [DbContext(typeof(SistemaControleDbContex))]
    [Migration("20241128145909_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_ControleDespesas.Model.Entity.ControleDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCompra")
                        .HasMaxLength(8)
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OutrosCustos")
                        .HasMaxLength(12)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco")
                        .HasMaxLength(12)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasMaxLength(12)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubCategoria")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasMaxLength(14)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ControleDespesa");
                });
#pragma warning restore 612, 618
        }
    }
}
